//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_InvestedHistory
    {
        public int InvestedHistoryID { get; set; }
        public int InvestorProjectID { get; set; }
        public int PersonID { get; set; }
        public Nullable<System.DateTime> InvestDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual z_InvestorProject z_InvestorProject { get; set; }
    }
}
