//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_InvestorProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public z_InvestorProject()
        {
            this.z_SolarPanelInfo = new HashSet<z_SolarPanelInfo>();
        }
    
        public int InvestorProjectID { get; set; }
        public string Name { get; set; }
        public string ProjectAddress { get; set; }
        public string ProjectZip { get; set; }
        public string ProjectCity { get; set; }
        public Nullable<System.DateTime> ProjectStart { get; set; }
        public string BankName { get; set; }
        public string BankNumber { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<z_SolarPanelInfo> z_SolarPanelInfo { get; set; }
    }
}
