//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_investeraDashboardPermission
    {
        public int id { get; set; }
        public int umbracoUserId { get; set; }
        public bool investeraDashBoardUser { get; set; }
    
        public virtual umbracoUser umbracoUser { get; set; }
    }
}
