//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umbraco2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_SolarPanelInfo
    {
        public int SolarPanelInfoID { get; set; }
        public Nullable<decimal> Power { get; set; }
        public string TypeName { get; set; }
    }
}
